# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 22:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crystal', '0003_auto_20161012_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questao',
            name='resposta',
        ),
    ]
