# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-14 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crystal', '0004_remove_questao_resposta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prova',
            name='dificuldade',
            field=models.IntegerField(choices=[(1, 'Muito fácil'), (2, 'Fácil'), (3, 'Normal'), (4, 'Difícil'), (5, 'Muito difícil')], default=3),
        ),
    ]
