# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-23 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crystal', '0005_auto_20161014_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questao',
            name='enunciado',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='questao',
            name='opcao1',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='questao',
            name='opcao2',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='questao',
            name='opcao3',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='questao',
            name='opcao4',
            field=models.CharField(max_length=150),
        ),
    ]
